name: admin
description: Rockstar Admin Panel
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.3

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^13.2.0

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  data_table_2: ^2.5.15
  fl_chart: ^0.69.0
  file_picker: ^8.1.2
  image_picker_web: ^4.0.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
